version: 0.0
os: linux
files:
  - source: /
    destination: /https://github.com/yasenn/apiks
permissions:
  - object: /https://github.com/yasenn/apiks
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
